---
sudo: false

language: python
python: "2.7"
cache: pip

addons:
  apt:
    packages:
    - python-pip

install:
  # Install Ansible.
  - pip install ansible==2.0.2.0

  # install dependent role
  - ansible-galaxy install --roles-path=tests/roles --role-file=tests/roles/requirements.yml

script:
  - "cd tests"

  # check syntax
  - "ansible-playbook -i inventory test.yml --syntax-check"

  # run playbook
  - "ansible-playbook -i inventory test.yml --connection=local"

  # run again to check if it is indempotent
  - >
    ansible-playbook -i inventory test.yml --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
