- name: prepare mysql dump restore
  template:
    src: "piwik.sql.j2"
    dest: "/tmp/piwik.sql"
    force: no

- name: restore dump
  mysql_db:
    name: "{{ piwik.db.name }}"
    target: "/tmp/piwik.sql"
    state: import
  ignore_errors: yes
