---
- name: set piwik_root
  set_fact:
    piwik_root: "{{ piwik_install_location | default( piwik.install_location ) }}/{{ piwik.unpack_dir }}"
    piwik_download_file: "{{ piwik.download.file_prefix }}-{{ piwik_download_version | default( piwik.download.version ) }}{{ piwik_download_file_extension | default( piwik.download.file_extension ) }}"

- name: create installation directory
  file:
    path:  "{{ piwik_install_location | default( piwik.install_location ) }}"
    owner: "{{ piwik_user | default( piwik.user ) }}"
    group: "{{ piwik_group | default( piwik.group ) }}"
    state: directory

# Fetch latest release
- name: "Fetch latest Piwik release"
  unarchive:
    copy:  no
    src:   "{{ piwik_download_url | default( piwik.download.url ) }}/{{ piwik_download_file }}"
    dest:  "{{ piwik_install_location | default( piwik.install_location ) }}"
    owner: "{{ piwik_user | default( piwik.user ) }}"
    group: "{{ piwik_group | default( piwik.group ) }}"
    creates: "{{ piwik_root }}"

# create config.ini.php with default settings
- name: "Create config.ini.php"
  template:
    src:   "config.ini.php.j2"
    dest:  "{{ piwik_root }}/config/config.ini.php"
    owner: "{{ piwik_web_user | default( piwik.web.user ) }}"
    group: "{{ piwik_web_user | default( piwik.web.user ) }}"
    mode:  0664
    force: no

# Create Piwik temp folders
- name: "Create Piwik temp folders"
  file:
    path:  "{{ piwik_root }}/{{ item }}"
    owner: "{{ piwik_web_user | default( piwik.web.user ) }}"
    group: "{{ piwik_web_group | default( piwik.web.group ) }}"
    mode:  0755
    state: directory
  with_items: "{{ piwik.web.dirs }}"

- name: setup database
  include: db.yml

- name: "call console commands"
  shell: "./console {{ item.1 }} > tmp/logs/ansible-piwik-command-{{ item.0 }}.log"
  args:
    chdir: "{{ piwik_root }}"
    creates: "{{ piwik_root }}/tmp/logs/ansible-piwik-command-{{ item.0 }}.log"
  with_indexed_items: "{{ piwik_commands }}"
