---
- name: set piwik_root
  set_fact:
    piwik_root: "{{ piwik_install_location | default( piwik.install_location ) }}/{{ piwik.unpack_dir }}"

- name: create installation directory
  file:
    path:  "{{ piwik_install_location | default( piwik.install_location ) }}"
    owner: "{{ piwik_user | default( piwik.user ) }}"
    group: "{{ piwik_group | default( piwik.group ) }}"
    state: directory

# Fetch latest release
- name: "Fetch latest Piwik release"
  unarchive:
    copy:  no
    src:   "{{ piwik_download_url | default( piwik.download.url ) }}/{{ piwik_download_file | default( piwik.download.file ) }}"
    dest:  "{{ piwik_install_location | default( piwik.install_location ) }}"
    owner: "{{ piwik_user | default( piwik.user ) }}"
    group: "{{ piwik_group | default( piwik.group ) }}"
    creates: "{{ piwik_root }}"

# create config.ini.php with default settings
- name: "Create config.ini.php"
  template:
    src:   "config.ini.php.j2"
    dest:  "{{ piwik_root }}/config/config.ini.php"
    owner: "{{ piwik_user | default( piwik.user ) }}"
    group: "{{ piwik_user | default( piwik.user ) }}"
    mode:  0664
